language: android
sudo: required

dist: trusty

android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.2
    - android-30
    - extra-android-m2repository

jdk:
  - openjdk11

notifications:
  email: false
before_install:
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - yes | sdkmanager --update
  - yes | sdkmanager --licenses

script:
  - ./gradlew clean
  - ./gradlew build
#  - ./gradlew assemble check
#  - ./gradlew checkstyle
#  - ./gradlew assembleRelease
