language: android
sudo: required

dist: trusty

android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.2
    - android-30
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

jdk:
  - openjdk11

notifications:
  email: false
before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean
  - ./gradlew build
#  - ./gradlew assemble check
#  - ./gradlew checkstyle
#  - ./gradlew assembleRelease
