language: android
sudo: required

dist: trusty

android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-30
    - extra-android-m2repository

jdk:
  - openjdk8

notifications:
  email: false
before_install:
 - chmod +x gradlew

script:
  - ./gradlew clean
  - ./gradlew assembleRelease
#  - ./gradlew assemble check
#  - ./gradlew checkstyle
#  - ./gradlew build
